name: aura2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
 
  flutter:
    sdk: flutter
  audioplayers_web: ^2.2.0
  timezone: ^0.9.1
  #latlng: any
  latlong2: ^0.8.0
  flutter_map: ^3.1.0
  #latlong: 0.6.1
  faker: ^2.1.0
  provider: ^6.0.5
  location: ^4.4.0
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  firebase_core_platform_interface: 4.5.2
  encrypt: ^5.0.1
  uuid: ^3.0.7
  shared_preferences: ^2.0.17
  flutter_launcher_icons: ^0.11.0
  audioplayers: ^3.0.1
  after_layout: ^1.2.0
  url_launcher: ^6.1.8
  cron: ^0.5.1
  get: ^4.6.5
  flutter_map_marker_cluster: ^1.0.2
  flutter_map_marker_popup: ^4.0.0
  animated_button_bar: ^1.0.0
  chips_choice_null_safety: ^2.0.6
  flutter_layout_grid: ^2.0.1
  compass_icon: ^1.0.4
  flutter_colorpicker: ^1.0.3





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  
  awesome_notifications: ^0.6.4+1
  #awesome_notifications_fcm: ^0.7.4+1
  swipedetector: ^1.2.0
  rename: ^2.1.1
  change_app_package_name: ^1.1.0
  cloud_functions: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo_aura_violet1.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_aura_violet.png
    - assets/images/AURA_VISUEL02.jpg
    - assets/images/logo.png
    - assets/Manufacture sur Seine Quartier Terre/reinventer-seine-manufacture-seine-amateur.jpg
    - assets/57 logements - Herzog et Demeuron/IMG_2681.jpeg
    - assets/Centre Ville de Montreuil sous Bois Alvaro Siza/Croquis Siza Centre Ville Montreuil.jpg
    - assets/La Grande Arche/IMG_3992.jpeg
    - assets/Fondation Louis Vuitton/IMG_1330.jpeg
    - assets/IMG_4027.jpeg
    - assets/IMG_2083.jpeg
    - assets/téléchargement (1).jpg
    - assets/téléchargement.jpg
    - assets/La Tour Triangle/La Tour Triangle.jpg
    - assets/Hôpital Cognacq-Jay - Toyo Ito/IMG_9574.jpeg
    - assets/Musée Quai Branly/IMG_3690.jpeg
    - assets/Espace de Méditation UNESCO - Tadao Ando/IMG_3819.jpeg
    - assets/Showroom Citroën/IMG_3651.jpeg
    - assets/57 logements - Herzog et Demeuron/IMG_2681.jpeg
    - assets/Fondation Cartier/IMG_2195.jpeg
    - assets/Galerie Marchande Gaîté Montparnasse/03_Gaîté_Montparnasse_MVRDV_©Ossip van Duivenbode.jpg
    - assets/Département des Arts de l_Islam du Louvre/PARIS_Departement-des-Arts-de-l-Islam-du-musee-du-Louvre_02b.jpg
    - assets/La Pyramide du Louvre/IMG_3222.jpeg
    - assets/La Nouvelle Saint Maritaine - SANAA/IMG_3967.jpeg
    - assets/La Canopée/IMG_3297.jpeg
    - assets/IMG_3353.jpeg
    - assets/Pavillon Mobile Art Chanel/chanel_mobile_art_pavilion-zaha_hadid_2_photo AA13.jpg
    - assets/Pushed Slab/IMG_5889.jpeg
    - assets/IMG_7619.jpeg
    - assets/Bibliothèque François Mitterand/IMG_6855.jpeg
    - assets/Cité de la mode/IMG_7176.jpeg
    - assets/La Cinémathèque Française/IMG_8448.jpeg
    - assets/Eden Bio/IMG_4174.jpeg
    - assets/La Philharmonie/IMG_4684.jpeg
    - assets/Cité de la mode/Le Parc Lavillette/IMG_4727.jpeg
    - assets/220 Logements rue de Meaux/IMG_2681.jpeg
    - assets/Siège Parti Communiste/IMG_4383.jpeg
    - assets/La Tour Bois Le Prêtre - Lacaton Vassal/IMG_0689.jpeg
    - assets/Emergence/IMG_0324.jpeg
    - assets/Tower Flower/IMG_0269.jpeg
    - assets/Beaubourg/IMG_3334.jpeg
    - assets/IMG_3334.JPG
    - assets/location-arrow-solid copie.png
    - assets/Cité de la mode/Le Tribunal de Paris/IMG_0321.jpeg
    - assets/Institut Monde Arabe/IMG_8831.jpeg
    - assets/Villa d_all_Ava - Oma/IMG_3076.jpeg
    - assets/images/marqueurViolet1.png
    - assets/images/Icon bâtiment.svg
    - assets/images/pyramide du louvre.jpg
    - assets/images/AURA_bouton_connecte_ plus_tard.png
    - assets/images/AURA_bouton_me_connecter.png
    - assets/images/AURA_bouton_minscrire.png
    - assets/images/AURA - bouton connecter plus tard_EN.png
    - assets/images/AURA - bouton me connecter_EN.png
    - assets/images/AURA - bouton m'inscrire_EN.png
    - assets/images/carte_earth_large.png
    - assets/images/marker/marqueurVioletFoncé.png
    - assets/images/marker/marqueurVioletFoncéCoeur.png
    - assets/images/marker/marqueurViolet.png
    - assets/images/marker/marqueurVioletFavori.png
    - assets/images/utilisateur.png
    - assets/images/icones/favori.png
    - assets/images/icones/audio.png
    - assets/images/icones/like.png
    - assets/images/icones/nord.png
    - assets/images/icones/partager.png
    - assets/images/icones/recherche.png
    - assets/images/marker/marqueurVioletFoncéSélectionné.png
    - assets/images/marker/marqueurVioletSélectionné.png
    - assets/images/marker/marqueurVioletFoncéSélectionnéCoeur.png
    - assets/images/marker/marqueurVioletSélectionnéCoeur.png
    - assets/images/WF_AUDIO_BOUTON_VOLUME.png
    - assets/images/WF_AUDIO_BOUTON_CROIX.png
    - assets/images/ICON_VOLUME.png
    - assets/images/icones/def.png
    - assets/images/icones/tags.png
    - assets/images/icones/abclogo.png
    - assets/images/icones/ICON_ABC.png
    - assets/images/icones/ICON_BOUTON ABC.png
    - assets/images/icones/ICON_LIVRE.png
    - assets/images/icones/ICON_CASE.png
    - assets/images/icones/AURA_AUDIO_BOUTON RACCOURCI.png
    - assets/images/ICON_VOLUME_VIOLET.png
    - assets/images/icones/ICON_CASE+ CLAIR.png
    - assets/images/icones/ICON_LIVRE CLAIR.png


    #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: CharisSIL
  #     fonts:
  #       - asset: assets/fonts/CharisSILR.ttf
  #       - asset: assets/fonts/CharisSILI.ttf
  #         style: italic
  #       - asset: assets/fonts/CharisSILB.ttf
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
